require('plugins')
require('options')
require('keybindings')
vim.g.tokyonight_style = "night"
-- vim.g.tokyonight_lualine_bold = true
vim.cmd('colorscheme tokyonight')
-- vim.cmd('colorscheme kanagawa')
-- vim.cmd('colorscheme moonfly')
-- vim.cmd('colorscheme omni')
require('treesitter-config')
require('lualine-config')
require('bufferline-config')
require('blankline-config')
require('nvim-tree-config')
require('autopairs-config')
require('whichkey-config')
require('telescope-config')
require('lsp')
require('comment-config')
require('highlight')
require('colorizer-config')
require('toggleterm-config')
require('luasnip-config')
