require('plugins')
require('options')
require('keybindings')
vim.cmd('colorscheme kanagawa')
require('treesitter-config')
require('lualine-config')
require('bufferline-config')
require('blankline-config')
require('nvim-tree-config')
require('autopairs-config')
require('whichkey-config')
require('telescope-config')
require('lsp')
require('comment-config')
require('highlight')
require('colorizer-config')
require('toggleterm-config')
