export WINEPREFIX="$HOME/.local/wineprefixes/default"
export CARGO_HOME="$HOME/.config/cargo"
export GTK_RC_FILES="$XDG_CONFIG_HOME/gtk-1.0/gtkrc"
export GTK2_RC_FILES="$XDG_CONFIG_HOME/gtk-2.0/gtkrc"
export GNUPGHOME="$HOME/.config/gnupg"
export PATH="$PATH:/home/maciej/.local/lib/python3.9/site-packages/"
export XAUTHORITY="$XDG_RUNTIME_DIR/Xauthority"
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export WGETRC="$XDG_CONFIG_HOME/wgetrc"
export "_JAVA_OPTIONS=-Djava.util.prefs.userRoot=$XDG_CONFIG_HOME/java"
export VISUAL=/usr/bin/nvim
export EDITOR=/usr/bin/nvim
export TERMINAL=/usr/bin/kitty
export PATH="$PATH:/home/maciej/.local/bin"
export KEYTIMEOUT=10
export BROWSER=qutebrowser
export GNUPGHOME="~/.config/gnupg"
export QT_QPA_PLATFORMTHEME="qt5ct"
export GIT_PAGER=cat
export WINEDLLOVERRIDES=winemenubuilder.exe=d
export PASSWORD_STORE_DIR="serwer/pass"
export XINITRC="$HOME/.config/X11/xinitrc"
